FROM node:alpine AS builder

ENV NODE_ENV production

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --include=dev

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/.next /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]